name: party-planner
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

env:
  DB_NAME: party
  DB_USERNAME: partyplanner
  DB_PASSWORD: PartyPlanner!!

jobs:
  testing:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env: 
          DB_NAME: ${{env.DB_NAME}}
          DB_PASSWORD: ${{env.DB_PASSWORD}}
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install 
          npm run lazy
deploy:
    runs-on: ubuntu-latest
    needs: testing
    steps:
    - name: ssh to pull latest version
      uses: fifsky/ssh-action@master
      with:
        command: |
          git pull frankie
          npm install
          npm run lazy
          forever restart -c 'npm start' .
        host: partyplanner.frankieyip.world
        user: ubuntu
        key: ${{secrets.SSH_PRIVATE_KEY}}